version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ship-app
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app 
      - /app/build
      - /app/node_modules
    command: npm run docker-start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
