# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a8261d9ad435418218bb43338657f542"
name = "Shiperman Shipping"
handle = "shiperman-shipping"
application_url = "https://encoding-kitty-difficulties-characterized.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dhl-test08.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_markets,write_shipping"

[auth]
redirect_urls = [
  "https://encoding-kitty-difficulties-characterized.trycloudflare.com/auth/callback",
  "https://encoding-kitty-difficulties-characterized.trycloudflare.com/auth/shopify/callback",
  "https://encoding-kitty-difficulties-characterized.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://totally-well-off-poetry.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://totally-well-off-poetry.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
