# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cfc509f26ffaa21469d0ba3b3f01a290"
name = "product-list"
handle = "product-list-37"
application_url = "https://d56a-122-160-255-97.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "devapptest2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_shipping,write_markets"

[auth]
redirect_urls = [
  "https://d56a-122-160-255-97.ngrok-free.app//callback",
  "https://d56a-122-160-255-97.ngrok-free.app//shopify/callback",
  "https://d56a-122-160-255-97.ngrok-free.app//api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
